version: '3.8'

services:
  pdfmerge:
    build: .
    ports:
      - "8585:8585"
    environment:
      - PORT=8585
      - BASE_URL=http://localhost
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8585/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/var/log/pdfmerge
