# curl -X POST http://localhost:8080/merge -H "Content-Type: application/json" -o merged.pdf -d '{ "name": "combined_docs", "urls": [ "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", "https://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf", "https://www.africau.edu/images/default/sample.pdf" ] }' 
POST http://localhost:8080/merge
content-type: application/json

{
  "name": "combined_docs",
  "urls": [
  "https://devone.aplikasi.web.id/birt/run?__report=report/one/fo/rpt_t_001.rptdesign&__format=pdf&username=ADMIN&PID=131891",
  "https://devone.aplikasi.web.id/birt/frameset?__report=report/one/lab/rpt_test_not_print.rptdesign&__format=pdf&username=ADMIN&PID=131890&tm=1699347726767"
  ]
}

